"""initial migration

Revision ID: 34cbcc341981
Revises: 
Create Date: 2026-02-24 12:27:45.705546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cbcc341981'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cycles_user_id_fkey'), 'cycles', type_='foreignkey')
    op.create_foreign_key(None, 'cycles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cycles', type_='foreignkey')
    op.create_foreign_key(op.f('cycles_user_id_fkey'), 'cycles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
