"""add cycle_logs table

Revision ID: ccfff0df9ab6
Revises: 34cbcc341981
Create Date: 2026-02-24 12:42:13.546975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfff0df9ab6'
down_revision: Union[str, Sequence[str], None] = '34cbcc341981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Enum('happy', 'neutral', 'sad', 'anxious', 'irritable', name='moodenum'), nullable=False),
    sa.Column('flow_intensity', sa.Enum('none', 'spotting', 'light', 'medium', 'heavy', name='flowintensityenum'), nullable=True),
    sa.Column('cramps', sa.Boolean(), nullable=True),
    sa.Column('headache', sa.Boolean(), nullable=True),
    sa.Column('fatigue', sa.Boolean(), nullable=True),
    sa.Column('acne', sa.Boolean(), nullable=True),
    sa.Column('bloating', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_logs_id'), 'cycle_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycle_logs_id'), table_name='cycle_logs')
    op.drop_table('cycle_logs')
    # ### end Alembic commands ###
